### ISSUE TITLE
Source for Postgres' binary format

### ISSUE THREAD

**Issue by pbrinkmeier** [nikita-volkov/postgresql-binary#19]
Hi, not sure where else to ask this.

I am wondering if you have a good primary source for figuring out the binary format that Postgres uses for transfer. I am currently in the process of implementing a small Postgres library for learning and I'm worried about future-proofing. I thought about simply checking out the Postgres source and looking at what it sends, but it would be cool if there was some sort of documentation on what kind of backwards compatibility Postgres offers for the binary format.

So if you could explain a little what you used to write the decoders that would be great!

**Comment by nikita-volkov** [comment]
Unfortunately there's no documentation on the binary format. I reverse engineered the [libpqtypes](https://github.com/pgagarinov/libpqtypes) lib, IIRC. Nowadays I would just go straight for the source of Postgres itself.

Regarding the stability of the format, I'm pretty sure it won't ever change in a backwards incompatible way. E.g., they even have format versioning bytes inside some data types (jsonb).

**Comment by pbrinkmeier** [comment]
Thanks for the reply, I'll check the source then and hope for the best. I might even take some inspiration from your own implementation, though I'll probably use `attoparsec`.
