### ISSUE TITLE
postgresql-binary-0.5.0 cannot compile its test suite

### ISSUE THREAD

**Issue by peti** [nikita-volkov/postgresql-binary#2]
The error is:

    executables/Tests.hs:18:18:
        Could not find module ‘PostgreSQLBinary.PTI’
        Perhaps you meant
          PostgreSQLBinary.Array (from postgresql-binary-0.5.0)

A complete build log can be found at http://hydra.cryp.to/build/501691/nixlog/3/raw.

**Comment by nikita-volkov** [comment]
Thank you. Fixed in 0.5.1
