### ISSUE TITLE
json-ast 0.3 support

### ISSUE THREAD

**Issue by bergmark** [nikita-volkov/postgresql-binary#6]
The test-suite for this package has been disabled in stackage because of this outdated dependency. When a fix is published to hackage could you please send a PR to re-enable the tests to stackage (it's in the skipped-tests section) or ping me?

Thanks!

**Comment by nikita-volkov** [comment]
Ah. It doesn't really matter. Just keep the test suites disabled. It's okay.

Thanks.

**Comment by bergmark** [comment]
Okay, thanks for letting me know!
